### model
model_name_or_path: /home/zhaochaoyang/yangfan/dataset/Qwen/Qwen2.5-VL-7B-Instruct
# model_name_or_path: /home/zhaochaoyang/yangfan/project/Grounded-RL-yf/checkpoints/sft/qwen2_5vl-7b/full/our_minio3format_7k
image_max_pixels: 2000000
image_min_pixels: 40000
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
flash_attn: fa2
deepspeed: examples/deepspeed/ds_z3_offload_config.json

### dataset
dataset: our_minio3format_7k_absolute
template: qwen2_vl
cutoff_len: 65536 #2048
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 0

### output
output_dir: /home/zhaochaoyang/yangfan/project/Grounded-RL-yf/checkpoints/sft/qwen2_5vl-7b/full/our_minio3format_7k_absolute
# output_dir: /home/zhaochaoyang/yangfan/project/Grounded-RL-yf/checkpoints/sft/qwen2_5vl-7b-full-our_minio3format_7k/full/our_minio3format_7k_absolute
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb #none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
